core/urls.py
from django.conf.global_settings import STATIC_ROOT
from django.conf.urls.static import static
from django.urls import path

from suggestclasses.settings import STATIC_URL, MEDIA_URL, MEDIA_ROOT, DEBUG
from . import views
from .visoes import suggest_view, enquete_view, profile_view
from .visoes import sugestao_letras_view
from .visoes import sugestao_geografia_view
from .visoes import sugestao_historia_view
from .visoes.sugestao_contabeis_view import sugestao_cont_list, sugestao_cont_manter, sugestao_cont_incluir, \
    sugestao_cont_editar, sugestao_cont_deletar

urlpatterns = [
    path('profile/<username>/', profile_view.profile, name='profile'),
    path('ajax/load-componentes-historico/', profile_view.load_componentes_historico, name='ajax_load_componentes_historico'),

    path('profile/historico_deletar/<int:pk>', profile_view.historico_deletar_componente, name='historico_deletar_componente'),

    path('usuario/cadastrar', views.cadastrar_usuario, name='Cadastro de Usuário'),
    path('usuario/logar', views.logar_usuario, name='Login de Usuário'),
    path('usuario/deslogar', views.deslogar_usuario, name='Logout de Usuário'),
    path('usuario/alterar_senha', views.alterar_senha, name='Alterar Senha de Usuário'),

    path('', views.index, name='index'),
    path('sobre', views.sobre, name='sobre_details'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('horarios_list/', views.horarios_list, name='horarios_list'),
    path('<int:horario_id>/', views.detail, name='detail'),
    path('curso/<int:curso_id>/', views.curso_detail, name='curso_detail'),
    path('curso/list/', views.curso_list, name='Lista de Cursos'),
    path('departamento/list/', views.departamento_list, name='Lista de Departamentos'),
    path('componente/list/', views.componente_list, name='Lista de Componentes Curriculares'),
    path('componentes/<int:pk>/', views.ComponenteDetailView.as_view(), name='componente_detalhar'),

    path('curriculo/list/', views.curriculo_list, name='Lista de Estruturas Curriculares'),
    path('docentes/list/', views.docentes_list, name='docentes_list'),
    path('docente/<int:pk>/', views.DocenteDetailView.as_view(), name='docente_detalhar'),

    path('salas/list/', views.search_salas, name='search_salas'),
    path('enquetes/list/', views.search_enquetes, name='search_enquetes'),
    path('enquetes/<int:pk>/', views.EnqueteDetailView.as_view(), name='enquete_detalhar'),
    path('enquetes/<int:pk>/componente/<int:cc_pk>/', views.enquete_votos_listar, name='enquete_votos_listar'),
    path('enquetes/<int:pk>/votar', views.enquete_votar, name='enquete_votar'),
    path('enquetes/<int:pk>/detalhar', views.enquete_detalhar_voto, name='enquete_detalhar_voto'),
    path('enquetes/<int:pk>/abastencao', views.enquete_abstencao, name='enquete_abstencao'),
    path('enquetes/<int:pk>/votos/manter', views.sugestao_solicitar, name='enquete_votos_manter'),
    path('enquetes/deletar/votos/<int:pk>/', views.enquete_deletar_voto, name='enquete_deletar_voto'),
    path('ajax/load-componente/', enquete_view.load_componente, name='ajax_load_componente'),

    path('flow/', views.flow_list, name='Lista de Fluxogramas'),
    path('flow/bsi/opcionais', views.flow_bsi_op, name='Fluxograma BSI - Opcionais'),
    path('flow/bsi-1b-h/', views.flow_bsi_1b_h, name='Fluxograma BSI - 01B - Horizontal'),

    path('flow/cont/', views.flow_cont, name='flow_cont'),
    path('flow/cont/opcionais', views.flow_cont_op, name='flow_cont_op'),

    path('flow/dir/', views.flow_dir, name='flow_dir'),
    path('flow/dir/opcionais', views.flow_dir_op, name='flow_dir_op'),

    path('flow/his-lic/', views.flow_his_lic, name='flow_his_lic'),
    path('flow/his-lic/opcionais', views.flow_his_lic_op, name='flow_his_lic_op'),

    path('flow/his-bac/', views.flow_his_bac, name='flow_his_bac'),
    path('flow/his-bac/opcionais', views.flow_his_bac_op, name='flow_his_bac_op'),

    path('flow/geo-lic/', views.flow_geo_lic, name='flow_geo_lic'),
    path('flow/geo-lic/opcionais', views.flow_geo_lic_op, name='flow_geo_lic_op'),

    path('flow/geo-bac/', views.flow_geo_bac, name='flow_geo_bac'),
    path('flow/geo-bac/opcionais', views.flow_geo_bac_op, name='flow_geo_bac_op'),

    path('flow/ped-h/', views.flow_ped_h, name='flow_ped_h'),
    path('flow/ped/opcionais', views.flow_ped_op, name='Fluxograma Pedagogia - Opcionais'),

    path('flow/let-esp/', views.flow_let_esp, name='flow_let_esp'),
    path('flow/let-esp/opcionais', views.flow_let_esp_op, name='flow_let_esp_op'),

    path('flow/let-por/', views.flow_let_por, name='flow_let_por'),
    path('flow/let-por/opcionais', views.flow_let_por_op, name='flow_let_por_op'),

    path('flow/let-ing/', views.flow_let_ing, name='flow_let_ing'),
    path('flow/let-ing/opcionais', views.flow_let_ing_op, name='flow_let_ing_op'),

    path('flow/mat-h/', views.flow_mat_h, name='flow_mat_h'),
    path('flow/mat/opcionais', views.flow_mat_op, name='flow_mat_op'),

    path('flow/adm/', views.flow_adm, name='flow_adm'),
    path('flow/adm/opcionais', views.flow_adm_op, name='flow_adm_op'),

    path('flow/tur/', views.flow_tur, name='flow_tur'),
    path('flow/tur/opcionais', views.flow_tur_op, name='flow_tur_op'),

    path('turmas/', views.turmas_list, name='turmas_list'),
    path('turmas/cont', views.turmas_cont, name='turmas_contabeis'),
    path('turmas/dir', views.turmas_dir, name='turmas_direito'),
    path('turmas/geo-bac', views.turmas_geo_bac, name='turmas_geografia_bac'),
    path('turmas/geo-lic', views.turmas_geo_lic, name='turmas_geografia_lic'),
    path('turmas/his-bac', views.turmas_his_bac, name='turmas_historia_bac'),
    path('turmas/his-lic', views.turmas_his_lic, name='turmas_historia_lic'),
    path('turmas/mat', views.turmas_mat, name='turmas_matemática'),
    path('turmas/bsi', views.turmas_bsi, name='turmas_sistemas'),
    path('turmas/ped', views.turmas_ped, name='turmas_pedagogia'),
    path('turmas/adm', views.turmas_adm, name='turmas_administracao'),
    path('turmas/tur', views.turmas_tur, name='turmas_turismo'),
    path('turmas/let-esp', views.turmas_let_esp, name='turmas_letras_esp'),
    path('turmas/let-por', views.turmas_let_por, name='turmas_letras_por'),
    path('turmas/let-ing', views.turmas_let_ing, name='turmas_letras_ing'),
    path('turmas/<int:pk>/', views.TurmaDetailView.as_view(), name='turma_detalhar'),

    path('sugestao/', views.sugestao_list, name='sugestao_list'),
    path('sugestao/<int:pk>/', views.SugestaoTurmaDetailView.as_view(), name='sugestao_detalhar'),
    path('ajax/load-docentes/', suggest_view.load_docentes, name='ajax_load_docentes'),
    path('ajax/check_vinculo_docente/', suggest_view.check_vinculo_docente, name='ajax_check_vinculo_docente'),
    path('ajax/load-vinculos/', suggest_view.load_vinculos, name='ajax_load_vinculos'),

    path('solicitacao/<int:pk>/', views.sugestao_solicitar, name='sugestao_solicitar'),
    path('solicitacao/listar/<int:pk>/', views.solicitacao_turma_listar, name='solicitacao_turma_listar'),
    path('solicitacao/deletar/<int:pk>/', views.solicitacao_deletar, name='solicitacao_deletar'),

    path('sugestao/adm/list', views.sugestao_adm_list, name='sugestao_adm_list'),
    path('sugestao/adm/manter', views.sugestao_adm_manter, name='sugestao_adm_manter'),
    path('sugestao/adm/incluir', views.sugestao_adm_incluir, name='sugestao_adm_incluir'),
    path('sugestao/adm/editar/<int:pk>/', views.sugestao_adm_editar, name='sugestao_adm_editar'),
    path('sugestao/adm/deletar/<int:pk>/', views.sugestao_adm_deletar, name='sugestao_adm_deletar'),

    path('sugestao/cont/list', sugestao_cont_list, name='sugestao_cont_list'),
    path('sugestao/cont/manter', sugestao_cont_manter, name='sugestao_cont_manter'),
    path('sugestao/cont/incluir', sugestao_cont_incluir, name='sugestao_cont_incluir'),
    path('sugestao/cont/editar/<int:pk>/', sugestao_cont_editar, name='sugestao_cont_editar'),
    path('sugestao/cont/deletar/<int:pk>/', sugestao_cont_deletar, name='sugestao_cont_deletar'),

    path('sugestao/dir/list', views.sugestao_dir_list, name='sugestao_dir_list'),
    path('sugestao/dir/manter', views.sugestao_dir_manter, name='sugestao_dir_manter'),
    path('sugestao/dir/incluir', views.sugestao_dir_incluir, name='sugestao_dir_incluir'),
    path('sugestao/dir/editar/<int:pk>/', views.sugestao_dir_editar, name='sugestao_dir_editar'),
    path('sugestao/dir/deletar/<int:pk>/', views.sugestao_dir_deletar, name='sugestao_dir_deletar'),

    path('sugestao/geo-bac', sugestao_geografia_view.sugestao_geo_bac_list, name='sugestao_geo_bac_list'),
    path('sugestao/geo-bac/manter', sugestao_geografia_view.sugestao_geo_bac_manter, name='sugestao_geo_bac_manter'),
    path('sugestao/geo-bac/incluir', sugestao_geografia_view.sugestao_geo_bac_incluir, name='sugestao_geo_bac_incluir'),
    path('sugestao/geo-bac/editar/<int:pk>/', sugestao_geografia_view.sugestao_geo_bac_editar, name='sugestao_geo_bac_editar'),
    path('sugestao/geo-bac/deletar/<int:pk>/', sugestao_geografia_view.sugestao_geo_bac_deletar, name='sugestao_geo_bac_deletar'),

    path('sugestao/geo-lic', sugestao_geografia_view.sugestao_geo_lic_list, name='sugestao_geo_lic_list'),
    path('sugestao/geo-lic/manter', sugestao_geografia_view.sugestao_geo_lic_manter, name='sugestao_geo_lic_manter'),
    path('sugestao/geo-lic/incluir', sugestao_geografia_view.sugestao_geo_lic_incluir, name='sugestao_geo_lic_incluir'),
    path('sugestao/geo-lic/editar/<int:pk>/', sugestao_geografia_view.sugestao_geo_lic_editar, name='sugestao_geo_lic_editar'),
    path('sugestao/geo-lic/deletar/<int:pk>/', sugestao_geografia_view.sugestao_geo_lic_deletar, name='sugestao_geo_lic_deletar'),

    path('sugestao/his-bac', sugestao_historia_view.sugestao_his_bac_list, name='sugestao_his_bac_list'),
    path('sugestao/his-bac/manter', sugestao_historia_view.sugestao_his_bac_manter, name='sugestao_his_bac_manter'),

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

from mysite import settings

urlpatterns = [
    path('core/', include('core.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

handler403 = 'core.views.error_403'

# if settings.DEBUG:
#     import debug_toolbar
#
#     urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

suggestclasses/urls.py
from django.contrib import admin
from django.urls import include, path

from suggestclasses import settings

urlpatterns = [
    path('suggestclasses/', include('core.urls')),
    path('suggestclasses/accounts/', include('django.contrib.auth.urls')),
    path('suggestclasses/admin/', admin.site.urls),
]

handler403 = 'core.views.error_403'

# if settings.DEBUG:
#     import debug_toolbar
#
#     urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm

from core.bo.curso import get_curso_by_codigo
from core.bo.curriculo import get_componentes_by_curso, get_componentes_by_curso_semestre, get_semestres_by_curso
from core.bo.enquetes import get_componentes_enquete
from core.bo.sevices import get_cc_by_estrutura, get_estrutura_by_curso
from core.dao.componente_dao import get_componentes_curriculares
from core.models import Discente, Historico, OrganizacaoCurricular, SugestaoTurma, Docente, ComponenteCurricular, Departamento, Sala, \
    VotoTurma


class CadastroUsuarioForm(UserCreationForm):
    username = forms.CharField(max_length=30, required=True,
                               help_text='Obrigatório. 30 caracteres ou menos. '
                                         'Letras minúsculas, números e @ . + - _ apenas.')
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.', label='Primeiro Nome')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.', label='Sobrenome')
    matricula = forms.CharField(max_length=15, required=True, help_text='Obrigatório. Sua matrícula na UFRN.',
                                label='Matrícula')
    email = forms.EmailField(max_length=254, required=True, help_text='Obrigatório. Informe um e-mail válido.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'matricula', 'email', 'password1', 'password2',)


class SugestaoTurmaForm(ModelForm):
    componente = forms.ModelChoiceField(queryset=ComponenteCurricular.objects.all().order_by('nome', 'codigo'),
                                        label='Componente Curricular')

    descricao_horario = forms.CharField(label='Horário da Turma',
                                        widget=forms.TextInput(attrs={'placeholder': 'Ex: 24M34'}))

    capacidade_aluno = forms.CharField(label='Vagas', max_length=3,
                                       help_text='Obrigatório. As vagas deve ser menor que a capacidade da sala.')

    local = forms.ModelChoiceField(queryset=Sala.objects.all().order_by('campus', 'nome'),
                                   label='Local', required=False)
    checked = forms.BooleanField(
        label='Verificar Choques em Optativas', initial=True,required=False)
    departamento = forms.ModelChoiceField(queryset=Departamento.objects.all().order_by('nome'),
                                          label='Departamento', required=False)

    docente = forms.ModelChoiceField(queryset=Docente.objects.all().order_by('nome', 'siape'), label='Docente',
                                     required=False)

    horario_docente = forms.CharField(label='Horário Docente',
                                      widget=forms.TextInput(attrs={'placeholder': 'Ex: 24M34'}),
                                      help_text='Obrigatório. Horário do docente na turma',
                                      required=False)

    ch_docente = forms.CharField(label='CH Docente',
                                 widget=forms.TextInput(attrs={'placeholder': 'Ex: 60'}),
                                 help_text='Obrigatório. Carga horária do docente em horas.',
                                 required=False)

    vinculos_docente = forms.CharField(label='Vínculos Docentes', widget=forms.HiddenInput, required=False)

    def __init__(self, *args, **kwargs):
        estrutura = kwargs.pop('estrutura')
        super(SugestaoTurmaForm, self).__init__(*args, **kwargs)
        self.fields['componente'].queryset = get_cc_by_estrutura(estrutura)
        self.fields['docente'].queryset = Docente.objects.none()

        if 'departamento' in self.data:
            try:
                departamento_id = int(self.data.get('departamento'))
                self.fields['docente'].queryset = \
                    Docente.objects.filter(departamento_id=departamento_id).order_by('nome')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty Docente queryset
        elif self.instance.pk:
            # TODO aqui seria o carregamento de Vínculos Docentes??
            print('forms.py - linha 67')
            # self.fields['docente'].queryset = self.instance.departamento.docente_set.order_by('nome')
            self.fields['docente'].queryset = Docente.objects.none()

    class Meta:
        model = SugestaoTurma
        fields = ['codigo_turma', 'componente', 'descricao_horario', 'local', 'capacidade_aluno']
        widgets = {
            'codigo_turma': forms.TextInput(attrs={'placeholder': '01'}),
        }
        labels = {
            'codigo_turma': 'Código Turma',
        }


class VotoTurmaForm(ModelForm):
    class Meta:
        model = VotoTurma
        fields = ['componente']

    def __init__(self, *args, **kwargs):
        enquete = kwargs.pop('enquete')
        super(VotoTurmaForm, self).__init__(*args, **kwargs)
        self.fields['componente'].queryset = get_componentes_enquete(enquete)

SEMESTER_CHOICES = (
    ("1", "1º Semestre"),
    ("2", "2º Semestre"),
    ("3", "3º Semestre"),
    ("4", "4º Semestre"),
    ("5", "5º Semestre"),
    ("6", "6º Semestre"),
    ("7", "7º Semestre"),
    ("8", "8º Semestre"),
    ("9", "9º Semestre"),
    ("10", "10º Semestre"),
    ("0", "Optativas"),
)

class HistoricoForm(ModelForm):
    semestre = forms.ChoiceField(choices = SEMESTER_CHOICES, label='Semestre do Curso')
    componente = forms.ModelChoiceField(queryset=ComponenteCurricular.objects.all(), label='Componente Cursado')
    curso = forms.CharField(label='Curso', widget=forms.HiddenInput, required=False)
    discente = forms.ModelChoiceField(queryset=Discente.objects.all(), label='Discente', widget=forms.HiddenInput, required=False)
    class Meta:
        model = Historico
        fields = ['semestre', 'componente', 'curso', 'discente']

    def __init__(self, *args, **kwargs):
        discente = kwargs.pop('discente')
        super(HistoricoForm, self).__init__(*args, **kwargs)
        curso = get_curso_by_codigo(discente.id_curso)
        self.initial['curso'] = discente.id_curso
        self.initial['discente'] = discente
        print(self.data)
        semestre = 1
        if self.data:
            semestre = self.data['semestre']
        self.fields['componente'].queryset = get_componentes_by_curso_semestre(curso=curso, semestre=semestre)
        # self.fields['semestre'].queryset = get_semestres_by_curso(curso)
        # self.fields['componente'].queryset = get_componentes_by_curso(curso=curso)

core/templates/core/sugestao/bsi.html
{% extends 'core/base.html' %}

{% block content %}

  <section class="page-section" id="horarios">
    <div class="container">

      <h2 class="page-section-heading text-center text-secondary mb-0">Sugestões de Turmas
        do Curso Sistemas de Informação</h2>
      <h4 class="text-center">Semestre: 2020.1</h4>
      <br />
      <div class="text-center" id="div_periodos" style="font-size: 90%">
        <form method="get">
          <fieldset>
            <input type="checkbox" id="1p" name="periodos" value="1">
            <label for="1p">1º Período</label>
            <input type="checkbox" id="2p" name="periodos" value="2">
            <label for="2p">2º Período</label>
            <input type="checkbox" id="3p" name="periodos" value="3">
            <label for="3p">3º Período</label>
            <input type="checkbox" id="4p" name="periodos" value="4">
            <label for="4p">4º Período</label>
            <input type="checkbox" id="5p" name="periodos" value="5">
            <label for="5p">5º Período</label>
            <input type="checkbox" id="6p" name="periodos" value="6">
            <label for="6p">6º Período</label>
            <input type="checkbox" id="7p" name="periodos" value="7">
            <label for="7p">7º Período</label>
            <input type="checkbox" id="8p" name="periodos" value="8">
            <label for="8p">8º Período</label>
            <input type="checkbox" id="0p" name="periodos" value="0">
            <label for="0p">Opcionais</label>
            <input type="checkbox" id="todos" name="periodos" value="100">
            <label for="todos">Todos</label>
          </fieldset>
          <button id="get_sugestoes" type="submit">Carregar Sugestões de Turmas</button>
        </form>
      </div>

      <br />
      <table class="table table-striped table-sm table-bordered">
        <thead class="thead-light">
          <tr align="center">
            <th scope="col">#</th>
            <th scope="col">Segunda</th>
            <th scope="col">Terça</th>
            <th scope="col">Quarta</th>
            <th scope="col">Quinta</th>
            <th scope="col">Sexta</th>
          </tr>
        </thead>
        <tbody>
          {% for semana in tt %}
            <tr>
              <th scope="row" align="center" width="10%" style="font-size: 12px">
                {{ semana.0.horario.ordem }}º: {{ semana.0.horario.hora_inicio }} - {{ semana.0.horario.hora_final }}
              </th>
              {% for th in semana %}
                <td align="center" width="18%">
                  {% for turma in th.turmas %}
                    <p  style="font-size: 10px">{{ turma.componente.codigo }} - T{{ turma.codigo_turma }} <br />
                      {{ turma.componente.nome }} <br />
                      {{ turma.siape }} <br />
                      {{ turma.local }} <br />
                      {{ turma.campus_turma }}</p>
                  {% endfor %}
                </td>
              {% endfor %}
            </tr>
          {% endfor %}
        <tbody>
      </table>
    </div>
  </section>
  <script>
    $(document).ready(function() {
      $('#get_sugestoes').click({
        serviceUrl: '/core/sugestao/bsi',
        paramName: 'periodos',
      });
    });
  </script>
{% endblock %}

core/templates/core/sugestao/confirm_delete.html
{% extends 'core/base.html' %}
{% block content %}
  <div class="container">
    <h2 class="page-section-heading text-center text-secondary mb-0">Excluir de Sugestão de Turma</h2>
    <br/>
    <div class="row">
      <div class="col-md-1 col-xs-1 col-sm-1"></div>
      <div class="col-md-10 col-xs-10 col-sm-10">
        <form method="post">
          {% csrf_token %}
          <div class="form-row">
            <div class="alert alert-warning">
              Tem certeza de que deseja excluir a Turma {{ object }}?
            </div>
          </div>
          <button type="submit" class="btn btn-danger">
            <span class="material-icons align-middle">
              delete
            </span>
            Excluir
          </button>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

core/templates/core/sugestao/docentes_list_option.html
<option value="">---------</option>
{% for docente in docentes %}
<option value="{{ docente.pk }}">{{ docente }}</option>
{% endfor %}

core/templates/core/sugestao/editar.html
{% extends 'core/base.html' %}
{% block title %} SuggestClasses - Editar de Sugestão de Turma {% endblock %}
{% block content %}

  <div class="container">
    <h2 class="page-section-heading text-center text-secondary mb-0">Editar de Sugestão de Turma</h2>
    <br/>
    <form id="SugestaoForm" method="post" data-docentes-url="{% url 'ajax_load_docentes' %}"
          check-vinculo-docente-url="{% url 'ajax_check_vinculo_docente' %}" novalidate>
      {% csrf_token %}
      {% for hidden_field in form.hidden_fields %}
        {{ hidden_field }}
      {% endfor %}

      {% for field in form.visible_fields %}
        <div class="form-group row">
          <label class="col-sm-2 col-form-label">{{ field.label_tag }}</label><br>
          {{ field }}
          {% if field.help_text %}
            <small style="color: grey">{{ field.help_text }}</small>
          {% endif %}
          {% for error in field.errors %}
            <p style="color: red">{{ error }}</p>
          {% endfor %}
        </div>
      {% endfor %}
      <table class="table table-sm table-responsive-sm">
        {% for field in form_sugestao.visible_fields %}
          <tr>
            <th class="align-middle">
              <label>{{ field.label_tag }}</label>
            </th>
            <td class="align-middle">{{ field }}
              {% if field.help_text %}
                <small style="color: grey">{{ field.help_text }}</small>
              {% endif %}
              {% for error in field.errors %}
                <p style="color: red">{{ error }}</p>
              {% endfor %}
            </td>
          </tr>
        {% endfor %}
        <tr>
          <td colspan="2"><input id="add_vinculo" type="button" value="Adicionar Docente" class="btn btn-primary"></td>
        </tr>
        <tr>
          <td colspan="2">
            <table class="table table-sm text-center" style="width: 100%">
              <thead>
              <tr>
                <th colspan="4">Vínculos Docentes</th>
              </tr>
              <tr>
                <th>Professor</th>
                <th>Horário</th>
                <th>Carga Horária</th>
                <th>Ações</th>
              </tr>
              </thead>
              <tbody id='table_vinculos'>
                {% include 'core/sugestao/vinculo_docente_list.html' %}
              </tbody>
            </table>
          </td>
        </tr>
      </table>
      <input type="hidden" name="next" value="{{ request.GET.next }}">
      <button type="submit" class="btn btn-primary">Salvar</button>
    </form>
  </div>
{% endblock content %}
{% block myscripts %}
<script>
    $("#id_departamento").change(function () {
      const url = $("#SugestaoForm").attr("data-docentes-url");  // get the url of the `load_cities` view
      const deptoId = $(this).val();  // get the selected country ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'departamento': deptoId       // add the country id to the GET parameters
        },
        success: function (data) {
          $("#id_docente").html(data);
        }
      });
    });

    let val_vinculos = $("#id_vinculos_docente").val()
    vinculos_json = val_vinculos? JSON.parse(val_vinculos) : null
    let lista = vinculos_json? vinculos_json.vinculos : []

    $("#add_vinculo").click(function () {
      const url = $("#SugestaoForm").attr("check-vinculo-docente-url")
      const turmaId = $("#id_codigo_turma").val()
      const componenteId = $("#id_componente").val()
      const docenteId = $("#id_docente").val()
      const desc_horarios = $("#id_horario_docente").val()
      const cargaHoraria = $("#id_ch_docente").val()
      const vinculos_docente = $("#id_vinculos_docente").val()

      const new_vinculo = {
        docente: docenteId,
        horarios: desc_horarios,
        carga_horaria: cargaHoraria,
        codigo_turma: turmaId,
        componente: componenteId,
      };

      const data_input = {
        vinculo: new_vinculo,
        vinculos_docente: vinculos_docente,
      }

      $.ajax({
        url: url,
        data: data_input,
        dataType: 'json',
        success: function (data) {
          let listaHTML = $("#table_vinculos")
          listaHTML.html(data.html_vinculos)

          if (!data.existe_docente && !data.houve_choque) {
            lista.push(new_vinculo);
          }

          let vinculos_json = JSON.stringify({vinculos:lista})
          $("#id_vinculos_docente").val(vinculos_json)
        }
      });
    });

    function remover_vinculo(docenteId) {
      console.log('Removendo docente: ' + docenteId)
      lista = lista.filter((item) => item.docente !== docenteId);

      let vinculos_json = JSON.stringify({vinculos:lista})
      $("#id_vinculos_docente").val(vinculos_json)

      const data_input = {
        sugestao_id: '{{ form.instance.pk }}',
        docente_removido: docenteId,
        vinculos_docente: vinculos_json,
      }

      $.ajax({
        url: "{% url 'ajax_load_vinculos' %}",
        data: data_input,
        success: function (data) {
          const listaHTML = $("#table_vinculos")
          listaHTML.html(data)
        }
      });
    }

    $(window).on('load',function(){
      console.log('Carrega vínculos de docentes ...')
      '{% for v in vinculos %}'
        lista.push({
          docente: '{{ v.docente.id }}',
          horarios: '{{ v.horarios }}',
          carga_horaria: '{{ v.carga_horaria }}',
        });
      '{% endfor %}'
      let vinculos_json = JSON.stringify({vinculos:lista})
      $("#id_vinculos_docente").val(vinculos_json)
    });
  </script>
{% endblock myscripts %}