core/urls.py
from django.conf.global_settings import STATIC_ROOT
from django.conf.urls.static import static
from django.urls import path

from suggestclasses.settings import STATIC_URL, MEDIA_URL, MEDIA_ROOT, DEBUG
from . import views
from .visoes import suggest_view, enquete_view, profile_view
from .visoes import sugestao_letras_view
from .visoes import sugestao_geografia_view
from .visoes import sugestao_historia_view
from .visoes.sugestao_contabeis_view import sugestao_cont_list, sugestao_cont_manter, sugestao_cont_incluir, \
    sugestao_cont_editar, sugestao_cont_deletar

urlpatterns = [
    path('profile/<username>/', profile_view.profile, name='profile'),
    path('ajax/load-componentes-historico/', profile_view.load_componentes_historico, name='ajax_load_componentes_historico'),

    path('profile/historico_deletar/<int:pk>', profile_view.historico_deletar_componente, name='historico_deletar_componente'),

    path('usuario/cadastrar', views.cadastrar_usuario, name='Cadastro de Usuário'),
    path('usuario/logar', views.logar_usuario, name='Login de Usuário'),
    path('usuario/deslogar', views.deslogar_usuario, name='Logout de Usuário'),
    path('usuario/alterar_senha', views.alterar_senha, name='Alterar Senha de Usuário'),

    path('', views.index, name='index'),
    path('sobre', views.sobre, name='sobre_details'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('horarios_list/', views.horarios_list, name='horarios_list'),
    path('<int:horario_id>/', views.detail, name='detail'),
    path('curso/<int:curso_id>/', views.curso_detail, name='curso_detail'),
    path('curso/list/', views.curso_list, name='Lista de Cursos'),
    path('departamento/list/', views.departamento_list, name='Lista de Departamentos'),
    path('componente/list/', views.componente_list, name='Lista de Componentes Curriculares'),
    path('componentes/<int:pk>/', views.ComponenteDetailView.as_view(), name='componente_detalhar'),

    path('curriculo/list/', views.curriculo_list, name='Lista de Estruturas Curriculares'),
    path('docentes/list/', views.docentes_list, name='docentes_list'),
    path('docente/<int:pk>/', views.DocenteDetailView.as_view(), name='docente_detalhar'),

    path('salas/list/', views.search_salas, name='search_salas'),
    path('enquetes/list/', views.search_enquetes, name='search_enquetes'),
    path('enquetes/<int:pk>/', views.EnqueteDetailView.as_view(), name='enquete_detalhar'),
    path('enquetes/<int:pk>/componente/<int:cc_pk>/', views.enquete_votos_listar, name='enquete_votos_listar'),
    path('enquetes/<int:pk>/votar', views.enquete_votar, name='enquete_votar'),
    path('enquetes/<int:pk>/detalhar', views.enquete_detalhar_voto, name='enquete_detalhar_voto'),
    path('enquetes/<int:pk>/abastencao', views.enquete_abstencao, name='enquete_abstencao'),
    path('enquetes/<int:pk>/votos/manter', views.sugestao_solicitar, name='enquete_votos_manter'),
    path('enquetes/deletar/votos/<int:pk>/', views.enquete_deletar_voto, name='enquete_deletar_voto'),
    path('ajax/load-componente/', enquete_view.load_componente, name='ajax_load_componente'),

    path('flow/', views.flow_list, name='Lista de Fluxogramas'),
    path('flow/bsi/opcionais', views.flow_bsi_op, name='Fluxograma BSI - Opcionais'),
    path('flow/bsi-1b-h/', views.flow_bsi_1b_h, name='Fluxograma BSI - 01B - Horizontal'),

    path('flow/cont/', views.flow_cont, name='flow_cont'),
    path('flow/cont/opcionais', views.flow_cont_op, name='flow_cont_op'),

    path('flow/dir/', views.flow_dir, name='flow_dir'),
    path('flow/dir/opcionais', views.flow_dir_op, name='flow_dir_op'),

    path('flow/his-lic/', views.flow_his_lic, name='flow_his_lic'),
    path('flow/his-lic/opcionais', views.flow_his_lic_op, name='flow_his_lic_op'),

    path('flow/his-bac/', views.flow_his_bac, name='flow_his_bac'),
    path('flow/his-bac/opcionais', views.flow_his_bac_op, name='flow_his_bac_op'),

    path('flow/geo-lic/', views.flow_geo_lic, name='flow_geo_lic'),
    path('flow/geo-lic/opcionais', views.flow_geo_lic_op, name='flow_geo_lic_op'),

    path('flow/geo-bac/', views.flow_geo_bac, name='flow_geo_bac'),
    path('flow/geo-bac/opcionais', views.flow_geo_bac_op, name='flow_geo_bac_op'),

    path('flow/ped-h/', views.flow_ped_h, name='flow_ped_h'),
    path('flow/ped/opcionais', views.flow_ped_op, name='Fluxograma Pedagogia - Opcionais'),

    path('flow/let-esp/', views.flow_let_esp, name='flow_let_esp'),
    path('flow/let-esp/opcionais', views.flow_let_esp_op, name='flow_let_esp_op'),

    path('flow/let-por/', views.flow_let_por, name='flow_let_por'),
    path('flow/let-por/opcionais', views.flow_let_por_op, name='flow_let_por_op'),

    path('flow/let-ing/', views.flow_let_ing, name='flow_let_ing'),
    path('flow/let-ing/opcionais', views.flow_let_ing_op, name='flow_let_ing_op'),

    path('flow/mat-h/', views.flow_mat_h, name='flow_mat_h'),
    path('flow/mat/opcionais', views.flow_mat_op, name='flow_mat_op'),

    path('flow/adm/', views.flow_adm, name='flow_adm'),
    path('flow/adm/opcionais', views.flow_adm_op, name='flow_adm_op'),

    path('flow/tur/', views.flow_tur, name='flow_tur'),
    path('flow/tur/opcionais', views.flow_tur_op, name='flow_tur_op'),

    path('turmas/', views.turmas_list, name='turmas_list'),
    path('turmas/cont', views.turmas_cont, name='turmas_contabeis'),
    path('turmas/dir', views.turmas_dir, name='turmas_direito'),
    path('turmas/geo-bac', views.turmas_geo_bac, name='turmas_geografia_bac'),
    path('turmas/geo-lic', views.turmas_geo_lic, name='turmas_geografia_lic'),
    path('turmas/his-bac', views.turmas_his_bac, name='turmas_historia_bac'),
    path('turmas/his-lic', views.turmas_his_lic, name='turmas_historia_lic'),
    path('turmas/mat', views.turmas_mat, name='turmas_matemática'),
    path('turmas/bsi', views.turmas_bsi, name='turmas_sistemas'),
    path('turmas/ped', views.turmas_ped, name='turmas_pedagogia'),
    path('turmas/adm', views.turmas_adm, name='turmas_administracao'),
    path('turmas/tur', views.turmas_tur, name='turmas_turismo'),
    path('turmas/let-esp', views.turmas_let_esp, name='turmas_letras_esp'),
    path('turmas/let-por', views.turmas_let_por, name='turmas_letras_por'),
    path('turmas/let-ing', views.turmas_let_ing, name='turmas_letras_ing'),
    path('turmas/<int:pk>/', views.TurmaDetailView.as_view(), name='turma_detalhar'),

    path('sugestao/', views.sugestao_list, name='sugestao_list'),
    path('sugestao/<int:pk>/', views.SugestaoTurmaDetailView.as_view(), name='sugestao_detalhar'),
    path('ajax/load-docentes/', suggest_view.load_docentes, name='ajax_load_docentes'),
    path('ajax/check_vinculo_docente/', suggest_view.check_vinculo_docente, name='ajax_check_vinculo_docente'),
    path('ajax/load-vinculos/', suggest_view.load_vinculos, name='ajax_load_vinculos'),

    path('solicitacao/<int:pk>/', views.sugestao_solicitar, name='sugestao_solicitar'),
    path('solicitacao/listar/<int:pk>/', views.solicitacao_turma_listar, name='solicitacao_turma_listar'),
    path('solicitacao/deletar/<int:pk>/', views.solicitacao_deletar, name='solicitacao_deletar'),

    path('sugestao/adm/list', views.sugestao_adm_list, name='sugestao_adm_list'),
    path('sugestao/adm/manter', views.sugestao_adm_manter, name='sugestao_adm_manter'),
    path('sugestao/adm/incluir', views.sugestao_adm_incluir, name='sugestao_adm_incluir'),
    path('sugestao/adm/editar/<int:pk>/', views.sugestao_adm_editar, name='sugestao_adm_editar'),
    path('sugestao/adm/deletar/<int:pk>/', views.sugestao_adm_deletar, name='sugestao_adm_deletar'),

    path('sugestao/cont/list', sugestao_cont_list, name='sugestao_cont_list'),
    path('sugestao/cont/manter', sugestao_cont_manter, name='sugestao_cont_manter'),
    path('sugestao/cont/incluir', sugestao_cont_incluir, name='sugestao_cont_incluir'),
    path('sugestao/cont/editar/<int:pk>/', sugestao_cont_editar, name='sugestao_cont_editar'),
    path('sugestao/cont/deletar/<int:pk>/', sugestao_cont_deletar, name='sugestao_cont_deletar'),

    path('sugestao/dir/list', views.sugestao_dir_list, name='sugestao_dir_list'),
    path('sugestao/dir/manter', views.sugestao_dir_manter, name='sugestao_dir_manter'),
    path('sugestao/dir/incluir', views.sugestao_dir_incluir, name='sugestao_dir_incluir'),
    path('sugestao/dir/editar/<int:pk>/', views.sugestao_dir_editar, name='sugestao_dir_editar'),
    path('sugestao/dir/deletar/<int:pk>/', views.sugestao_dir_deletar, name='sugestao_dir_deletar'),

    path('sugestao/geo-bac', sugestao_geografia_view.sugestao_geo_bac_list, name='sugestao_geo_bac_list'),
    path('sugestao/geo-bac/manter', sugestao_geografia_view.sugestao_geo_bac_manter, name='sugestao_geo_bac_manter'),
    path('sugestao/geo-bac/incluir', sugestao_geografia_view.sugestao_geo_bac_incluir, name='sugestao_geo_bac_incluir'),
    path('sugestao/geo-bac/editar/<int:pk>/', sugestao_geografia_view.sugestao_geo_bac_editar, name='sugestao_geo_bac_editar'),
    path('sugestao/geo-bac/deletar/<int:pk>/', sugestao_geografia_view.sugestao_geo_bac_deletar, name='sugestao_geo_bac_deletar'),

    path('sugestao/geo-lic', sugestao_geografia_view.sugestao_geo_lic_list, name='sugestao_geo_lic_list'),
    path('sugestao/geo-lic/manter', sugestao_geografia_view.sugestao_geo_lic_manter, name='sugestao_geo_lic_manter'),
    path('sugestao/geo-lic/incluir', sugestao_geografia_view.sugestao_geo_lic_incluir, name='sugestao_geo_lic_incluir'),
    path('sugestao/geo-lic/editar/<int:pk>/', sugestao_geografia_view.sugestao_geo_lic_editar, name='sugestao_geo_lic_editar'),
    path('sugestao/geo-lic/deletar/<int:pk>/', sugestao_geografia_view.sugestao_geo_lic_deletar, name='sugestao_geo_lic_deletar'),

    path('sugestao/his-bac', sugestao_historia_view.sugestao_his_bac_list, name='sugestao_his_bac_list'),
    path('sugestao/his-bac/manter', sugestao_historia_view.sugestao_his_bac_manter, name='sugestao_his_bac_manter'),

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

from mysite import settings

urlpatterns = [
    path('core/', include('core.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

handler403 = 'core.views.error_403'

# if settings.DEBUG:
#     import debug_toolbar
#
#     urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

suggestclasses/urls.py
from django.contrib import admin
from django.urls import include, path

from suggestclasses import settings

urlpatterns = [
    path('suggestclasses/', include('core.urls')),
    path('suggestclasses/accounts/', include('django.contrib.auth.urls')),
    path('suggestclasses/admin/', admin.site.urls),
]

handler403 = 'core.views.error_403'

# if settings.DEBUG:
#     import debug_toolbar
#
#     urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm

from core.bo.curso import get_curso_by_codigo
from core.bo.curriculo import get_componentes_by_curso, get_componentes_by_curso_semestre, get_semestres_by_curso
from core.bo.enquetes import get_componentes_enquete
from core.bo.sevices import get_cc_by_estrutura, get_estrutura_by_curso
from core.dao.componente_dao import get_componentes_curriculares
from core.models import Discente, Historico, OrganizacaoCurricular, SugestaoTurma, Docente, ComponenteCurricular, Departamento, Sala, \
    VotoTurma


class CadastroUsuarioForm(UserCreationForm):
    username = forms.CharField(max_length=30, required=True,
                               help_text='Obrigatório. 30 caracteres ou menos. '
                                         'Letras minúsculas, números e @ . + - _ apenas.')
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.', label='Primeiro Nome')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.', label='Sobrenome')
    matricula = forms.CharField(max_length=15, required=True, help_text='Obrigatório. Sua matrícula na UFRN.',
                                label='Matrícula')
    email = forms.EmailField(max_length=254, required=True, help_text='Obrigatório. Informe um e-mail válido.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'matricula', 'email', 'password1', 'password2',)


class SugestaoTurmaForm(ModelForm):
    componente = forms.ModelChoiceField(queryset=ComponenteCurricular.objects.all().order_by('nome', 'codigo'),
                                        label='Componente Curricular')

    descricao_horario = forms.CharField(label='Horário da Turma',
                                        widget=forms.TextInput(attrs={'placeholder': 'Ex: 24M34'}))

    capacidade_aluno = forms.CharField(label='Vagas', max_length=3,
                                       help_text='Obrigatório. As vagas deve ser menor que a capacidade da sala.')

    local = forms.ModelChoiceField(queryset=Sala.objects.all().order_by('campus', 'nome'),
                                   label='Local', required=False)
    checked = forms.BooleanField(
        label='Verificar Choques em Optativas', initial=True,required=False)
    departamento = forms.ModelChoiceField(queryset=Departamento.objects.all().order_by('nome'),
                                          label='Departamento', required=False)

    docente = forms.ModelChoiceField(queryset=Docente.objects.all().order_by('nome', 'siape'), label='Docente',
                                     required=False)

    horario_docente = forms.CharField(label='Horário Docente',
                                      widget=forms.TextInput(attrs={'placeholder': 'Ex: 24M34'}),
                                      help_text='Obrigatório. Horário do docente na turma',
                                      required=False)

    ch_docente = forms.CharField(label='CH Docente',
                                 widget=forms.TextInput(attrs={'placeholder': 'Ex: 60'}),
                                 help_text='Obrigatório. Carga horária do docente em horas.',
                                 required=False)

    vinculos_docente = forms.CharField(label='Vínculos Docentes', widget=forms.HiddenInput, required=False)

    def __init__(self, *args, **kwargs):
        estrutura = kwargs.pop('estrutura')
        super(SugestaoTurmaForm, self).__init__(*args, **kwargs)
        self.fields['componente'].queryset = get_cc_by_estrutura(estrutura)
        self.fields['docente'].queryset = Docente.objects.none()

        if 'departamento' in self.data:
            try:
                departamento_id = int(self.data.get('departamento'))
                self.fields['docente'].queryset = \
                    Docente.objects.filter(departamento_id=departamento_id).order_by('nome')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty Docente queryset
        elif self.instance.pk:
            # TODO aqui seria o carregamento de Vínculos Docentes??
            print('forms.py - linha 67')
            # self.fields['docente'].queryset = self.instance.departamento.docente_set.order_by('nome')
            self.fields['docente'].queryset = Docente.objects.none()

    class Meta:
        model = SugestaoTurma
        fields = ['codigo_turma', 'componente', 'descricao_horario', 'local', 'capacidade_aluno']
        widgets = {
            'codigo_turma': forms.TextInput(attrs={'placeholder': '01'}),
        }
        labels = {
            'codigo_turma': 'Código Turma',
        }


class VotoTurmaForm(ModelForm):
    class Meta:
        model = VotoTurma
        fields = ['componente']

    def __init__(self, *args, **kwargs):
        enquete = kwargs.pop('enquete')
        super(VotoTurmaForm, self).__init__(*args, **kwargs)
        self.fields['componente'].queryset = get_componentes_enquete(enquete)

SEMESTER_CHOICES = (
    ("1", "1º Semestre"),
    ("2", "2º Semestre"),
    ("3", "3º Semestre"),
    ("4", "4º Semestre"),
    ("5", "5º Semestre"),
    ("6", "6º Semestre"),
    ("7", "7º Semestre"),
    ("8", "8º Semestre"),
    ("9", "9º Semestre"),
    ("10", "10º Semestre"),
    ("0", "Optativas"),
)

class HistoricoForm(ModelForm):
    semestre = forms.ChoiceField(choices = SEMESTER_CHOICES, label='Semestre do Curso')
    componente = forms.ModelChoiceField(queryset=ComponenteCurricular.objects.all(), label='Componente Cursado')
    curso = forms.CharField(label='Curso', widget=forms.HiddenInput, required=False)
    discente = forms.ModelChoiceField(queryset=Discente.objects.all(), label='Discente', widget=forms.HiddenInput, required=False)
    class Meta:
        model = Historico
        fields = ['semestre', 'componente', 'curso', 'discente']

    def __init__(self, *args, **kwargs):
        discente = kwargs.pop('discente')
        super(HistoricoForm, self).__init__(*args, **kwargs)
        curso = get_curso_by_codigo(discente.id_curso)
        self.initial['curso'] = discente.id_curso
        self.initial['discente'] = discente
        print(self.data)
        semestre = 1
        if self.data:
            semestre = self.data['semestre']
        self.fields['componente'].queryset = get_componentes_by_curso_semestre(curso=curso, semestre=semestre)
        # self.fields['semestre'].queryset = get_semestres_by_curso(curso)
        # self.fields['componente'].queryset = get_componentes_by_curso(curso=curso)

core/templates/core/usuario/alterar_senha.html
{% extends 'core/base.html' %}

{% block content %}

  <div class="container">

    <h3 class="page-section-heading text-center text-secondary mb-0">Alterar Senha de Usuário</h3>
      <br />
      <form method="post">
        {% csrf_token %}

        <div class="form-group">
            {{form_senha.old_password.errors}}
            <label>Senha antiga: </label>
            {{form_senha.old_password}}
        </div>

        <div class="form-group">
            {{form_senha.new_password1.errors}}
            <label>Nova senha: </label>
            {{form_senha.new_password1}}
        </div>

        <div class="form-group">
            {{form_senha.new_password2.errors}}
            <label>Confirmação de senha: </label>
            {{form_senha.new_password2}}
        </div>

        <div class="form-group">
            <input type="submit" value="Alterar" class="btn btn-primary">
        </div>
    </form>
  </div>
{% endblock %}

core/templates/core/usuario/cadastro.html
{% extends 'core/base.html' %}
{% block title %}Suggest Classes - Cadastro de Usuário{% endblock %}
{% block content %}

  <div class="container">

    <h3 class="page-section-heading text-center text-secondary mb-0">Cadastro de Usuário</h3>
    <br/>
    <div>
      <form method="post">
        {% csrf_token %}
        <table>
          {% for field in form_usuario %}
            <tr class="align-middle">
              <th class="align-middle"><label>{{ field.label_tag }}</label></th>
              <td>{{ field }}
                {% for error in field.errors %}
                  <p style="color: red">{{ error }}</p>
                {% endfor %}
                {% if field.help_text %}
                  <small style="color: grey">{{ field.help_text|safe }}</small>
                {% endif %}
              </td>
            </tr>
          {% endfor %}
        </table>
        <div class="form-group">
          <input type="submit" value="Cadastrar" class="btn btn-primary">
        </div>
      </form>
    </div>
  </div>
{% endblock %}

core/templates/core/usuario/componentes_list_option.html
<option value="">---------</option>
{% for componente in componentes %}
<option value="{{ componente.pk }}">{{ componente }}</option>
{% endfor %}

core/templates/core/usuario/confirm_delete_historico.html
{% extends 'core/base.html' %}
{% block content %}
  <div class="container">
    <h2 class="page-section-heading text-center text-secondary mb-0">Excluir de Componentes do Histórico</h2>
    <br/>
    <div class="row">
      <div class="col-md-1 col-xs-1 col-sm-1"></div>
      <div class="col-md-10 col-xs-10 col-sm-10">
        <form method="post">
          {% csrf_token %}
          <div class="form-row">
            <div class="alert alert-warning">
              Tem certeza de que deseja excluir o Componente {{ object.componente }} do seu histórico?
            </div>
          </div>
          <button type="submit" class="btn btn-danger">
            <span class="material-icons align-middle">
              delete
            </span>
            Excluir
          </button>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

core/templates/core/usuario/profile_discente.html
{% extends 'core/base.html' %}

{% block content %}

  <section class="page-section" id="perfil_discente">
    <div class="container">

      <div id="perfil_discente" class="center text-center form-group">
        <h3 class="page-section-heading text-center text-secondary mb-0">Perfil do Discente</h3>
      </div>

      <ul class="nav nav-pills nav-justified">
        <li class="nav-item">
          <a class="nav-link {% if tab_active == 'usuario' %}active{% endif %}" data-toggle="tab" href="#usuario">Usuário</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" data-toggle="tab" href="#horarios_atual">
            Horários {{ ano_periodo_atual }}
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" data-toggle="tab" href="#horarios">
            Horários {{ ano_periodo }}
          </a>
        </li>
        <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#solicitacoes">Solicitações {{ ano_periodo }}</a></li>
        <li class="nav-item"><a class="nav-link {% if tab_active == 'historico' %}active{% endif %}" data-toggle="tab" href="#historico">Histórico</a></li>
      </ul>

      <div class="tab-content">
        <div id="usuario" class="tab-pane container {% if tab_active == 'usuario' %}active{% endif %}">
          <table class="table table-striped table-sm table-bordered">
            <tr>
              <td class="font-weight-bold" width="20%">Username</td>
              <td>{{ usuario.username }}</td>
            </tr>
            <tr>
              <td class="font-weight-bold" width="20%">Nome</td>
              <td>{{ usuario.get_full_name }}</td>
            </tr>
            <tr>
              <td class="font-weight-bold" width="20%">Email</td>
              <td>{{ usuario.email }}</td>
            </tr>
            <tr>
              <td class="font-weight-bold" width="20%">Grupos</td>
              <td>{{ grupos }}</td>
            </tr>
            <tr>
              <td class="font-weight-bold" width="20%">Data de Cadastro</td>
              <td>{{ usuario.date_joined }}</td>
            </tr>
          </table>
          <table class="table table-striped table-sm table-bordered">
            <tr>
              <td class="font-weight-bold" width="20%">Matricula</td>
              <td>{{ perfil.matricula }}</td>
            </tr>
            <tr>
              <td class="font-weight-bold" width="20%">Nome</td>
              <td>{{ perfil.nome_discente }}</td>
            </tr>
            <tr>
              <td class="font-weight-bold" width="20%">Dados do Ingresso</td>
              <td>{{ perfil.ano_ingresso }}.{{ perfil.periodo_ingresso }} - {{ perfil.forma_ingresso }}</td>
            </tr>
            <tr>
              <td class="font-weight-bold" width="20%">Tipo Discente</td>
              <td> {{ perfil.tipo_discente }}</td>
            </tr>
            <tr>
              <td class="font-weight-bold" width="20%">Status</td>
              <td>{{ perfil.status }}</td>
            </tr>
            <tr>
              <td class="font-weight-bold" width="20%">Curso</td>
              <td>{{ perfil.nome_curso }}</td>
            </tr>
            <tr>
              <td class="font-weight-bold" width="20%">Unidade</td>
              <td>{{ perfil.nome_unidade }}</td>
            </tr>
            <tr>
              <td class="font-weight-bold" width="20%">Unidade Gestora</td>
              <td>{{ perfil.nome_unidade_gestora }}</td>
            </tr>
          </table>
        </div>
        <div id="horarios_atual" class="tab-pane container fade">
          <div id="avisos">
            <p class="alert-info">O Horário Atual é montado a partir de suas solicitações no semestre anterior, pois isso pode estar vazio.</p>
          </div>
          {% include 'core/usuario/discente/horarios_atual_periodo.html' %}
        </div>
        <div id="horarios" class="tab-pane container fade">
          {% include 'core/usuario/discente/horarios_prox_periodo.html' %}
        </div>
        <div id="solicitacoes" class="tab-pane container fade">
          <table class="table table-striped table-sm table-bordered">
          <tr class="text-center">
            <th>Turma</th>
            <th>Componente</th>
            <th>Semestre</th>
            <th>Docente</th>
            <th>Horário</th>
            <th colspan="2">Ações</th>
          </tr>
          {% for solicitacao in solicitacao_list %}
            <tr>
              <td class="align-middle text-center">{{ solicitacao.turma.codigo_turma }}</td>
              <td class="align-middle text-left">{{ solicitacao.turma.componente }}</td>
              <td class="align-middle text-center">{{ solicitacao.turma.semestre }}</td>
              <td class="align-middle text-center">
                {% include 'core/sugestao/vinculos_docente_exibir.html' with turma=solicitacao.turma %}
              </td>
              <td class="align-middle text-center">{{ solicitacao.turma.descricao_horario }}</td>
              <td class="align-middle text-center">
                <a href="{% url 'sugestao_detalhar' solicitacao.turma.pk %}">
                  <button type="button" class="btn btn-info">
                    <span class="material-icons align-middle">
                      find_in_page
                    </span>
                    Detalhar
                  </button>
                </a>
              </td>
              <td class="align-middle text-center">
                <a href="{% url solicitacao_deletar_link solicitacao.pk %}?next={{ request.path|urlencode }}">
                  <button type="button" class="btn btn-danger">
                    <span class="material-icons align-middle">
                      delete
                    </span>
                    Excluir
                  </button>
                </a>
              </td>
            </tr>
          {% empty %}
            <tr>
              <td class="align-middle text-center" colspan="6">Não há Solicitações de Turmas cadastradas!</td>
            </tr>
          {% endfor %}
        </table>
        </div>
        <div id="historico" class="tab-pane container fade {% if tab_active == 'historico' %}active{% endif %}">
          {% include 'core/usuario/historico.html' %}
        </div>
      </div>
    </div>
  </section>
{% endblock %}

{% block myscripts %}
<script>
  {% if tab_active %}
    $("#{{tab_active}}").addClass("show")
  {% endif %}
</script>
<script>
  $("#id_semestre").change(function () {
    const semestre_id = $(this).val();
    const curso_id = $("#id_curso").val()

    $.ajax({
      url: "{% url 'ajax_load_componentes_historico' %}",
      data: {
        'semestre_id': semestre_id,
        'curso_id': curso_id
      },
      success: function (data) {
        $("#id_componente").html(data);
      }
    });
  });
</script>
{% endblock myscripts %}